name: Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/node-deployment-learning

            pwd
            ls

            docker --version
            docker compose version

            git pull origin master

            sudo docker compose down

            sudo docker compose up --build -d
